#!/bin/ruby

require 'yaml'
require 'tmpdir'

filename_base = "addons"
filename_yaml = "#{filename_base}.yaml"
filename_yml = "#{filename_base}.yml"

filename =
  if File.exist?(filename_yaml)
    filename_yaml
  elsif File.exist?(filename_yml)
    filename_yml
  else
    nil
  end

if filename.nil?
  puts "addons.yaml not found"
  exit 1
end

config = YAML.safe_load_file(filename)

config.each do |name, addon_config|
  puts "Checking addon #{name}"
  Dir.mktmpdir do |dir|
    Dir.chdir(dir) do
      puts "Clone from #{addon_config['url']} into #{`pwd`}"
      puts `git clone #{addon_config['url']} .`
      puts `ls -la addons/#{name}`
    end
  end
end
